### ISSUE TITLE
'BertConfig' object has no attribute 'attention_head'  AttributeError: 'BertConfig' object has no attribute 'src_dropout_prob'

### ISSUE THREAD

**Issue by liuyan-design** [INFORMSJoC/2022.0285#4]
Traceback (most recent call last):
  File "train_classifier_linear.py", line 49, in <module>
    fw.train()
  File "/root/autodl-tmp/2022.0285/src/framework.py", line 62, in train
    model = BertClause.from_pretrained(os.path.join(self.config.model_dir, self.config.model_name), clause_max_len=self.config.clause_max_len, max_len=self.config.max_len)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1170, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/root/autodl-tmp/2022.0285/src/cross_encoder.py", line 48, in __init__
    config.co_num_attention_heads = config.attention_head
AttributeError: 'BertConfig' object has no attribute 'attention_head'

将cross_encoder.py中 config.co_num_attention_heads = config.attention_head改为：
config.co_num_attention_heads = config.num_attention_heads。此报错消失，但是会出现新的错误：

Traceback (most recent call last):
  File "train_classifier_linear.py", line 49, in <module>
    fw.train()
  File "/root/autodl-tmp/2022.0285/src/framework.py", line 62, in train
    model = BertClause.from_pretrained(os.path.join(self.config.model_dir, self.config.model_name), clause_max_len=self.config.clause_max_len, max_len=self.config.max_len)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1170, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/root/autodl-tmp/2022.0285/src/cross_encoder.py", line 54, in __init__
    self.src_dropout = nn.Dropout(self.config.src_dropout_prob)
AttributeError: 'BertConfig' object has no attribute 'src_dropout_prob'

环境配置如下：（关键库版本和作者要求的一样）
Package            Version
------------------ -----------
certifi            2024.8.30
charset-normalizer 3.3.2
click              8.1.7
filelock           3.16.1
huggingface-hub    0.0.8
idna               3.10
joblib             1.4.2
numpy              1.24.4
OpenCC             1.1.0
packaging          24.1
pillow             10.4.0
pip                24.2
PyYAML             6.0.2
regex              2024.9.11
requests           2.32.3
sacremoses         0.1.1
scikit-learn       1.3.2
scipy              1.10.1
setuptools         75.1.0
threadpoolctl      3.5.0
tokenizers         0.10.3
torch              1.8.0+cu111
torchaudio         0.8.0
torchvision        0.9.0+cu111
tqdm               4.66.5
transformers       4.7.0
typing_extensions  4.12.2
urllib3            2.2.3
wheel              0.44.0

**Comment by ArthurMLi** [comment]
This might help:This file might fix it

https://bit.ly/4eugCty

you may need to install the c compiler
